name: stockscape
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#version.Name+versionCode
version: 1.1.5+16

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  firebase_core: ^3.7.0
  cupertino_icons: ^1.0.2
  firebase_analytics: ^11.3.4
  firebase_crashlytics: ^4.1.4
  firebase_performance: ^0.10.0+9
  appsflyer_sdk: ^6.12.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  firebase_app_check: ^0.3.1+5
  google_adsense:
    path: ../../../flutter/packages/google_adsense
  js_interop: ^0.0.1
  go_router: ^14.1.0
  devicelocale: ^0.8.1
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true