name: adsense_mobile
description: Mobile App implementation of AdSense plugin
version: 0.0.2

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  adsense_platform_interface: ^0.0.1
  #    path: ../adsense_platform_interface
  google_mobile_ads: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: adsense
    platforms:
      android:
        dartPluginClass: AdsenseMobile
        fileName: adsense_mobile.dart
      ios:
        dartPluginClass: AdsenseMobile
        fileName: adsense_mobile.dart