name: adsense_web
description: Web implementation of AdSense plugin
version: 0.0.2

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  adsense_platform_interface: ^0.0.1
#    path: ../adsense_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    implements: adsense
    platforms:
      web:
        pluginClass: AdsenseWeb
        fileName: adsense_web.dart