// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7LrXlA9pbQ8Shy0kLua_Fr2NI2JMSrOM',
    appId: '1:1012971110099:web:1b3021332aa726b0d85e26',
    messagingSenderId: '1012971110099',
    projectId: 'stockscape',
    authDomain: 'stockscape-de170.firebaseapp.com',
    storageBucket: 'stockscape.appspot.com',
    measurementId: 'G-YMLFSVGEW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Qcp4SoxtN5WcdAwE_B_2gspgkiKdFCk',
    appId: '1:1012971110099:android:a7cd2cd1ac778edcd85e26',
    messagingSenderId: '1012971110099',
    projectId: 'stockscape',
    storageBucket: 'stockscape.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtqxHpaE614fnrIGn6VyVFC660efWUrJg',
    appId: '1:1012971110099:ios:a316ed977e13301dd85e26',
    messagingSenderId: '1012971110099',
    projectId: 'stockscape',
    storageBucket: 'stockscape.appspot.com',
    iosBundleId: 'com.visokolov.stockscape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtqxHpaE614fnrIGn6VyVFC660efWUrJg',
    appId: '1:1012971110099:ios:5226c11eee37dcf0d85e26',
    messagingSenderId: '1012971110099',
    projectId: 'stockscape',
    storageBucket: 'stockscape.appspot.com',
    iosBundleId: 'com.visokolov.stockscape.RunnerTests',
  );
}
