name: adsense_platform_interface
description: Platform interface for AdSense plugin
version: 0.0.2


environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  adsense_web: ^0.0.1
  #    path: ../adsense_web
  adsense_mobile: ^0.0.1
#    path: ../adsense_mobile


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0